using System;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.XR.iOS;

public class PlaneManager : MonoBehaviour {

    public GameObject planePrefab;
    private UnityARAnchorManager unityARAnchorManager;
    private bool planePlaced = false;
	private GameObject gameBase;
	public Camera mainCamera;
	public UnityARCameraManager cameraManager;
    public bool enableARKit;
    public Transform coinBox;
    
    // Use this for initialization
    void Start() {
        Time.timeScale = 1f;
        if (enableARKit) {
            gameBase = GameObject.Find("Game Base");
            gameBase.SetActive(false);
            var cameraParent = GameObject.Find("CameraParent");
            cameraParent.transform.position = new Vector3();
            cameraParent.transform.rotation = new Quaternion();
            if (m_HitTransform) {
                Debug.Log("Plane already exists");
                PlacePlane();
            } else {
                m_HitTransform = new GameObject().transform;
                unityARAnchorManager = new UnityARAnchorManager();
                UnityARUtility.InitializePlanePrefab(planePrefab);
            }
		} else {
            coinBox.gameObject.SetActive(true);
			Destroy(cameraManager.gameObject);
			Destroy(mainCamera.gameObject.GetComponent<UnityARVideo>());
			Destroy(mainCamera.gameObject.GetComponent<UnityARCameraNearFar>());
			mainCamera.clearFlags = CameraClearFlags.SolidColor;
		}
	}

    static Transform m_HitTransform;
    static Transform oldCameraTrans;
    public float maxRayDistance = 30.0f;
    public LayerMask collisionLayer = 1 << 10;  //ARKitPlane layer

	void PlacePlane() {
		gameBase.SetActive(true);
        gameBase.transform.position = m_HitTransform.position;
        if (oldCameraTrans == null) {
            oldCameraTrans = mainCamera.transform;
        }
        Vector3 dir = oldCameraTrans.position - m_HitTransform.position;
        dir.y = 0;
        gameBase.transform.rotation = Quaternion.LookRotation(-dir);
		planePlaced = true;
        // Place Coin Box
        dir = m_HitTransform.position - oldCameraTrans.position;
        dir.z = -1.5f;
        coinBox.position = dir + oldCameraTrans.position;
        coinBox.gameObject.SetActive(true);
        // Turn off plane detection
        GameObject.Find("Camera Manager").GetComponent<UnityARCameraManager>().planeDetectionOFF();
        if (unityARAnchorManager != null) {
            unityARAnchorManager.Destroy();
        }
        DontDestroyOnLoad(m_HitTransform);
        DontDestroyOnLoad(oldCameraTrans);
	}

    bool HitTestWithResultType(ARPoint point, ARHitTestResultType resultTypes) {
        List<ARHitTestResult> hitResults = UnityARSessionNativeInterface.GetARSessionNativeInterface().HitTest(point, resultTypes);
        if (hitResults.Count > 0) {
            foreach (var hitResult in hitResults) {
                Debug.Log("Got hit!");
                m_HitTransform.position = UnityARMatrixOps.GetPosition(hitResult.worldTransform);
                m_HitTransform.rotation = UnityARMatrixOps.GetRotation(hitResult.worldTransform);
                Debug.Log(string.Format("x:{0:0.######} y:{1:0.######} z:{2:0.######}", m_HitTransform.position.x, m_HitTransform.position.y, m_HitTransform.position.z));
                return true;
            }
		} else {
			Debug.Log("Ggg");
		}
        return false;
	}

    void Update() {
		if (enableARKit && !planePlaced) {
#if UNITY_EDITOR   //we will only use this script on the editor side, though there is nothing that would prevent it from working on device
            if (Input.GetMouseButtonDown(0)) {
                Ray ray = Camera.main.ScreenPointToRay(Input.mousePosition);
                RaycastHit hit;

                //we'll try to hit one of the plane collider gameobjects that were generated by the plugin
                //effectively similar to calling HitTest with ARHitTestResultType.ARHitTestResultTypeExistingPlaneUsingExtent
                if (Physics.Raycast(ray, out hit, maxRayDistance, collisionLayer)) {
                    //we're going to get the position from the contact point
                    m_HitTransform.position = hit.point;
                    Debug.Log(string.Format("x:{0:0.######} y:{1:0.######} z:{2:0.######}", m_HitTransform.position.x, m_HitTransform.position.y, m_HitTransform.position.z));

                    //and the rotation from the transform of the plane collider
                    m_HitTransform.rotation = hit.transform.rotation;
                    PlacePlane();
                }
            }
#else
            if (Input.touchCount > 0 && m_HitTransform != null)
            {
                var touch = Input.GetTouch(0);
                if (touch.phase == TouchPhase.Began || touch.phase == TouchPhase.Moved)
                {
                    var screenPosition = Camera.main.ScreenToViewportPoint(touch.position);
                    ARPoint point = new ARPoint {
                        x = screenPosition.x,
                        y = screenPosition.y
                    };

                    // prioritize reults types
                    ARHitTestResultType[] resultTypes = {
                        ARHitTestResultType.ARHitTestResultTypeExistingPlaneUsingExtent, 
                        // if you want to use infinite planes use this:
                        //ARHitTestResultType.ARHitTestResultTypeExistingPlane,
                        ARHitTestResultType.ARHitTestResultTypeHorizontalPlane, 
                        ARHitTestResultType.ARHitTestResultTypeFeaturePoint
                    }; 
                    
                    foreach (ARHitTestResultType resultType in resultTypes)
                    {
                        if (HitTestWithResultType (point, resultType))
						{
                            PlacePlane();
                            return;
                        }
                    }
                }
            }
#endif
        }
    }

    void OnDestroy() {
		if (enableARKit && unityARAnchorManager != null) {
            unityARAnchorManager.Destroy();
		}
    }

}
